# Generated by Django 4.2.20 on 2025-03-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='file_url',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file',
            field=models.FileField(default='media/default.txt', upload_to='media/'),
            preserve_default=False,
        ),
    ]
